FROM python:3.12-slim

RUN adduser --disabled-password --gecos "" --home "/nonexistent" --shell "/sbin/nologin" --no-create-home "app"


WORKDIR /opt/fil-rouge/

COPY ./requirements.txt .
COPY ./main.py .
#COPY ./env .

RUN pip install -r ./requirements.txt

USER app:app

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0" ]