FROM ubuntu:22.04

WORKDIR /opt/fil-rouge/

RUN apt-get update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN pip install -r ./requirements.txt

COPY ./requirements.txt .
COPY ./main.py .

ENTRYPOINT [ "uvicorn", "main:app", "--host", "0.0.0.0" ]